[
  { "soal": "Aku punya leher tapi tidak punya kepala. Siapakah aku?", "jawaban": "baju" },
  { "soal": "Makin malam makin terang, aku apa?", "jawaban": "bulan" },
  { "soal": "Aku bisa menghilang saat kau sebut namaku. Siapa aku?", "jawaban": "hening" },
  { "soal": "Apa yang bisa naik tapi tidak turun?", "jawaban": "umur" },
  { "soal": "Apa yang selalu datang tapi tak pernah tiba?", "jawaban": "besok" },
  { "soal": "Aku punya kaki tapi tidak bisa berjalan. Apakah aku?", "jawaban": "meja" },
  { "soal": "Apa yang selalu basah saat mengeringkan?", "jawaban": "handuk" },
  { "soal": "Benda apa yang dilempar malah kembali?", "jawaban": "boomerang" },
  { "soal": "Benda apa yang kalau dipakai tetap dingin?", "jawaban": "kipas" },
  { "soal": "Kenapa ayam menyeberang jalan?", "jawaban": "karena ingin ke seberang" },
  { "soal": "Apa yang bulat, kecil, tapi bikin orang pusing?", "jawaban": "utang" },
  { "soal": "Apa yang bisa dilihat tapi tidak bisa disentuh?", "jawaban": "bayangan" },
  { "soal": "Semakin banyak diambil, semakin besar. Apakah aku?", "jawaban": "lubang" },
  { "soal": "Aku selalu bersama kamu tapi kamu gak bisa pegang aku. Apa aku?", "jawaban": "bayangan" },
  { "soal": "Aku bisa terbang tanpa sayap dan bisa jatuh tanpa terluka. Apa aku?", "jawaban": "waktu" },
  { "soal": "Apa yang bisa memanjat tapi tidak punya kaki?", "jawaban": "suara" },
  { "soal": "Semua orang punya tapi tak bisa dilihat. Apakah aku?", "jawaban": "pikiran" },
  { "soal": "Benda apa yang tiap hari dibuka tutup tapi tidak marah?", "jawaban": "pintu" },
  { "soal": "Apa yang bisa masuk rumah tanpa izin?", "jawaban": "udara" },
  { "soal": "Apa yang gak bisa dilihat tapi bisa dirasakan?", "jawaban": "angin" },
  { "soal": "Apa yang selalu kamu bawa tapi gak pernah kamu lihat?", "jawaban": "punggung" },
  { "soal": "Aku bisa nyala tanpa api. Aku apa?", "jawaban": "lampu" },
  { "soal": "Apa yang kalau berdiri dia miring, tapi kalau tidur dia lurus?", "jawaban": "pensil" },
  { "soal": "Apa yang warnanya putih tapi bukan kapas?", "jawaban": "awan" },
  { "soal": "Aku lahir dari api, tapi aku basah. Siapakah aku?", "jawaban": "abu" },
  { "soal": "Apa yang bisa berputar tapi tidak jalan?", "jawaban": "kipas angin" },
  { "soal": "Apa yang kalau disimpan dia hilang?", "jawaban": "rahasia" },
  { "soal": "Apa yang bisa mengikat tapi tidak kelihatan?", "jawaban": "janji" },
  { "soal": "Aku selalu di belakang kamu, tapi kamu gak bisa lihat aku. Apa aku?", "jawaban": "masa lalu" },
  { "soal": "Apa yang selalu benar tapi jarang dipercaya?", "jawaban": "logika" },
  { "soal": "Aku punya tangan tapi gak punya jari. Siapa aku?", "jawaban": "jam" },
  { "soal": "Apa yang punya mata tapi tidak bisa melihat?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa menggigit?", "jawaban": "sisir" },
  { "soal": "Apa yang punya lidah tapi tidak bisa bicara?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar?", "jawaban": "tangga" },
  { "soal": "Apa yang punya mulut tapi tidak pernah makan?", "jawaban": "sungai" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium?", "jawaban": "teko" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berjalan?", "jawaban": "tempat tidur" },
  { "soal": "Apa yang punya sayapi tapi tidak bisa terbang?", "jawaban": "rumah" },
  { "soal": "Apa yang punya ekor tapi tidak bisa digerakkan?", "jawaban": "bola lampu" },
  { "soal": "Apa yang punya daun tapi bukan pohon?", "jawaban": "buku" },
  { "soal": "Apa yang punya akar tapi bukan tanaman?", "jawaban": "gigi" },
  { "soal": "Apa yang punya kulit tapi bukan manusia atau hewan?", "jawaban": "jeruk" },
  { "soal": "Apa yang punya tulang tapi bukan makhluk hidup?", "jawaban": "tulang ikan" },
  { "soal": "Apa yang punya darah tapi bukan manusia atau hewan?", "jawaban": "buah" },
  { "soal": "Apa yang punya hati tapi tidak bisa merasa?", "jawaban": "pisau" },
  { "soal": "Apa yang punya wajah tapi tidak bisa tersenyum?", "jawaban": "jam" },
  { "soal": "Apa yang punya kepala tapi tidak punya otak?", "jawaban": "paku" },
  { "soal": "Apa yang punya bibir tapi tidak bisa bicara?", "jawaban": "gelas" },
  { "soal": "Apa yang punya punggung tapi tidak bisa membungkuk?", "jawaban": "buku" },
  { "soal": "Apa yang punya perut tapi tidak bisa lapar?", "jawaban": "tas" },
  { "soal": "Apa yang punya leher tapi tidak punya kepala?", "jawaban": "baju" },
  { "soal": "Apa yang punya lengan tapi tidak bisa memeluk?", "jawaban": "kursi" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berlari?", "jawaban": "meja" },
  { "soal": "Apa yang punya jari tapi tidak bisa menggenggam?", "jawaban": "sarung tangan" },
  { "soal": "Apa yang punya rambut tapi tidak bisa disisir?", "jawaban": "jagung" },
  { "soal": "Apa yang punya mata tapi tidak bisa menangis?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa tertawa?", "jawaban": "gergaji" },
  { "soal": "Apa yang punya lidah tapi tidak bisa menjilat?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar musik?", "jawaban": "kunci pas" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium bunga?", "jawaban": "teko" },
  { "soal": "Apa yang punya mulut tapi tidak bisa minum?", "jawaban": "sungai" },
  { "soal": "Apa yang punya sayap tapi tidak bisa terbang tinggi?", "jawaban": "ayam" },
  { "soal": "Apa yang punya ekor tapi tidak bisa mengibas?", "jawaban": "bola lampu" },
  { "soal": "Apa yang punya daun tapi tidak hijau?", "jawaban": "buku" },
  { "soal": "Apa yang punya akar tapi tidak di tanah?", "jawaban": "rambut" },
  { "soal": "Apa yang punya kulit tapi tidak berdarah?", "jawaban": "apel" },
  { "soal": "Apa yang punya tulang tapi tidak sakit kalau patah?", "jawaban": "ikan" },
  { "soal": "Apa yang punya darah tapi tidak merah?", "jawaban": "kelapa" },
  { "soal": "Apa yang punya hati tapi tidak berdetak?", "jawaban": "artichoke" },
  { "soal": "Apa yang punya wajah tapi tidak punya emosi?", "jawaban": "jam dinding" },
  { "soal": "Apa yang punya kepala tapi tidak punya pikiran?", "jawaban": "paku" },
  { "soal": "Apa yang punya bibir tapi tidak bisa mencium?", "jawaban": "toples" },
  { "soal": "Apa yang punya punggung tapi tidak bisa dibelakangi?", "jawaban": "gunung" },
  { "soal": "Apa yang punya perut tapi tidak bisa dicuci?", "jawaban": "kapal" },
  { "soal": "Apa yang punya leher tapi tidak bisa tenggorokan?", "jawaban": "botol" },
  { "soal": "Apa yang punya lengan tapi tidak bisa angkat tangan?", "jawaban": "kursi" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berjalan?", "jawaban": "meja" },
  { "soal": "Apa yang punya jari tapi tidak bisa mengetik?", "jawaban": "sarung tangan" },
  { "soal": "Apa yang punya rambut tapi tidak bisa diwarnai?", "jawaban": "jagung" },
  { "soal": "Apa yang punya mata tapi tidak bisa melihat indahnya dunia?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa mengunyah?", "jawaban": "sisir" },
  { "soal": "Apa yang punya lidah tapi tidak bisa merasakan manis?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar cerita?", "jawaban": "tangga" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium aroma?", "jawaban": "teko" },
  { "soal": "Apa yang punya mulut tapi tidak bisa berbicara?", "jawaban": "sungai" },
  { "soal": "Apa yang punya sayap tapi tidak bisa terbang?", "jawaban": "rumah" },
  { "soal": "Apa yang punya ekor tapi tidak bisa digerakkan?", "jawaban": "bola lampu" },
  { "soal": "Apa yang punya daun tapi tidak tumbuh?", "jawaban": "buku" },
  { "soal": "Apa yang punya akar tapi tidak butuh air?", "jawaban": "persamaan matematika" },
  { "soal": "Apa yang punya kulit tapi tidak bisa dilukai?", "jawaban": "jeruk" },
  { "soal": "Apa yang punya tulang tapi tidak bisa patah?", "jawaban": "tulang ikan" },
  { "soal": "Apa yang punya darah tapi tidak mengalir?", "jawaban": "buah" },
  { "soal": "Apa yang punya hati tapi tidak bisa cinta?", "jawaban": "pisau" },
  { "soal": "Apa yang punya wajah tapi tidak bisa tersenyum?", "jawaban": "jam" },
  { "soal": "Apa yang punya kepala tapi tidak punya otak?", "jawaban": "paku" },
  { "soal": "Apa yang punya bibir tapi tidak bisa mencium?", "jawaban": "gelas" },
  { "soal": "Apa yang punya punggung tapi tidak bisa membungkuk?", "jawaban": "buku" },
  { "soal": "Apa yang punya perut tapi tidak bisa kenyang?", "jawaban": "tas" },
  { "soal": "Apa yang punya leher tapi tidak punya kepala?", "jawaban": "baju" },
  { "soal": "Apa yang punya lengan tapi tidak bisa memeluk?", "jawaban": "kursi" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berlari?", "jawaban": "meja" },
  { "soal": "Apa yang punya jari tapi tidak bisa menggenggam?", "jawaban": "sarung tangan" },
  { "soal": "Apa yang punya rambut tapi tidak bisa disisir?", "jawaban": "jagung" },
  { "soal": "Apa yang punya mata tapi tidak bisa menangis?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa tertawa?", "jawaban": "gergaji" },
  { "soal": "Apa yang punya lidah tapi tidak bisa menjilat?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar?", "jawaban": "tangga" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium?", "jawaban": "teko" },
  { "soal": "Apa yang punya mulut tapi tidak bisa minum?", "jawaban": "sungai" },
  { "soal": "Apa yang punya sayap tapi tidak bisa terbang?", "jawaban": "ayam" },
  { "soal": "Apa yang punya ekor tapi tidak bisa mengibas?", "jawaban": "bola lampu" },
  { "soal": "Apa yang punya daun tapi tidak hijau?", "jawaban": "buku" },
  { "soal": "Apa yang punya akar tapi tidak di tanah?", "jawaban": "rambut" },
  { "soal": "Apa yang punya kulit tapi tidak berdarah?", "jawaban": "apel" },
  { "soal": "Apa yang punya tulang tapi tidak sakit kalau patah?", "jawaban": "ikan" },
  { "soal": "Apa yang punya darah tapi tidak merah?", "jawaban": "kelapa" },
  { "soal": "Apa yang punya hati tapi tidak berdetak?", "jawaban": "artichoke" },
  { "soal": "Apa yang punya wajah tapi tidak punya emosi?", "jawaban": "jam dinding" },
  { "soal": "Apa yang punya kepala tapi tidak punya pikiran?", "jawaban": "paku" },
  { "soal": "Apa yang punya bibir tapi tidak bisa mencium?", "jawaban": "toples" },
  { "soal": "Apa yang punya punggung tapi tidak bisa dibelakangi?", "jawaban": "gunung" },
  { "soal": "Apa yang punya perut tapi tidak bisa dicuci?", "jawaban": "kapal" },
  { "soal": "Apa yang punya leher tapi tidak bisa tenggorokan?", "jawaban": "botol" },
  { "soal": "Apa yang punya lengan tapi tidak bisa angkat tangan?", "jawaban": "kursi" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berjalan?", "jawaban": "meja" },
  { "soal": "Apa yang punya jari tapi tidak bisa mengetik?", "jawaban": "sarung tangan" },
  { "soal": "Apa yang punya rambut tapi tidak bisa diwarnai?", "jawaban": "jagung" },
  { "soal": "Apa yang punya mata tapi tidak bisa melihat indahnya dunia?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa mengunyah?", "jawaban": "sisir" },
  { "soal": "Apa yang punya lidah tapi tidak bisa merasakan manis?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar cerita?", "jawaban": "tangga" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium aroma?", "jawaban": "teko" },
  { "soal": "Apa yang punya mulut tapi tidak bisa berbicara?", "jawaban": "sungai" },
  { "soal": "Apa yang punya sayap tapi tidak bisa terbang?", "jawaban": "rumah" },
  { "soal": "Apa yang punya ekor tapi tidak bisa digerakkan?", "jawaban": "bola lampu" },
  { "soal": "Apa yang punya daun tapi tidak tumbuh?", "jawaban": "buku" },
  { "soal": "Apa yang punya akar tapi tidak butuh air?", "jawaban": "persamaan matematika" },
  { "soal": "Apa yang punya kulit tapi tidak bisa dilukai?", "jawaban": "jeruk" },
  { "soal": "Apa yang punya tulang tapi tidak bisa patah?", "jawaban": "tulang ikan" },
  { "soal": "Apa yang punya darah tapi tidak mengalir?", "jawaban": "buah" },
  { "soal": "Apa yang punya hati tapi tidak bisa cinta?", "jawaban": "pisau" },
  { "soal": "Apa yang punya wajah tapi tidak bisa tersenyum?", "jawaban": "jam" },
  { "soal": "Apa yang punya kepala tapi tidak punya otak?", "jawaban": "paku" },
  { "soal": "Apa yang punya bibir tapi tidak bisa mencium?", "jawaban": "gelas" },
  { "soal": "Apa yang punya punggung tapi tidak bisa membungkuk?", "jawaban": "buku" },
  { "soal": "Apa yang punya perut tapi tidak bisa kenyang?", "jawaban": "tas" },
  { "soal": "Apa yang punya leher tapi tidak punya kepala?", "jawaban": "baju" },
  { "soal": "Apa yang punya lengan tapi tidak bisa memeluk?", "jawaban": "kursi" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berlari?", "jawaban": "meja" },
  { "soal": "Apa yang punya jari tapi tidak bisa menggenggam?", "jawaban": "sarung tangan" },
  { "soal": "Apa yang punya rambut tapi tidak bisa disisir?", "jawaban": "jagung" },
  { "soal": "Apa yang punya mata tapi tidak bisa menangis?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa tertawa?", "jawaban": "gergaji" },
  { "soal": "Apa yang punya lidah tapi tidak bisa menjilat?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar?", "jawaban": "tangga" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium?", "jawaban": "teko" },
  { "soal": "Apa yang punya mulut tapi tidak bisa minum?", "jawaban": "sungai" },
  { "soal": "Apa yang punya sayap tapi tidak bisa terbang?", "jawaban": "ayam" },
  { "soal": "Apa yang punya ekor tapi tidak bisa mengibas?", "jawaban": "bola lampu" },
  { "soal": "Apa yang punya daun tapi tidak hijau?", "jawaban": "buku" },
  { "soal": "Apa yang punya akar tapi tidak di tanah?", "jawaban": "rambut" },
  { "soal": "Apa yang punya kulit tapi tidak berdarah?", "jawaban": "apel" },
  { "soal": "Apa yang punya tulang tapi tidak sakit kalau patah?", "jawaban": "ikan" },
  { "soal": "Apa yang punya darah tapi tidak merah?", "jawaban": "kelapa" },
  { "soal": "Apa yang punya hati tapi tidak berdetak?", "jawaban": "artichoke" },
  { "soal": "Apa yang punya wajah tapi tidak punya emosi?", "jawaban": "jam dinding" },
  { "soal": "Apa yang punya kepala tapi tidak punya pikiran?", "jawaban": "paku" },
  { "soal": "Apa yang punya bibir tapi tidak bisa mencium?", "jawaban": "toples" },
  { "soal": "Apa yang punya punggung tapi tidak bisa dibelakangi?", "jawaban": "gunung" },
  { "soal": "Apa yang punya perut tapi tidak bisa dicuci?", "jawaban": "kapal" },
  { "soal": "Apa yang punya leher tapi tidak bisa tenggorokan?", "jawaban": "botol" },
  { "soal": "Apa yang punya lengan tapi tidak bisa angkat tangan?", "jawaban": "kursi" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berjalan?", "jawaban": "meja" },
  { "soal": "Apa yang punya jari tapi tidak bisa mengetik?", "jawaban": "sarung tangan" },
  { "soal": "Apa yang punya rambut tapi tidak bisa diwarnai?", "jawaban": "jagung" },
  { "soal": "Apa yang punya mata tapi tidak bisa melihat indahnya dunia?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa mengunyah?", "jawaban": "sisir" },
  { "soal": "Apa yang punya lidah tapi tidak bisa merasakan manis?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar cerita?", "jawaban": "tangga" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium aroma?", "jawaban": "teko" },
  { "soal": "Apa yang punya mulut tapi tidak bisa berbicara?", "jawaban": "sungai" },
  { "soal": "Apa yang punya sayap tapi tidak bisa terbang?", "jawaban": "rumah" },
  { "soal": "Apa yang punya ekor tapi tidak bisa digerakkan?", "jawaban": "bola lampu" },
  { "soal": "Apa yang punya daun tapi tidak tumbuh?", "jawaban": "buku" },
  { "soal": "Apa yang punya akar tapi tidak butuh air?", "jawaban": "persamaan matematika" },
  { "soal": "Apa yang punya kulit tapi tidak bisa dilukai?", "jawaban": "jeruk" },
  { "soal": "Apa yang punya tulang tapi tidak bisa patah?", "jawaban": "tulang ikan" },
  { "soal": "Apa yang punya darah tapi tidak mengalir?", "jawaban": "buah" },
  { "soal": "Apa yang punya hati tapi tidak bisa cinta?", "jawaban": "pisau" },
  { "soal": "Apa yang punya wajab tapi tidak bisa tersenyum?", "jawaban": "jam" },
  { "soal": "Apa yang punya kepala tapi tidak punya otak?", "jawaban": "paku" },
  { "soal": "Apa yang punya bibir tapi tidak bisa mencium?", "jawaban": "gelas" },
  { "soal": "Apa yang punya punggung tapi tidak bisa membungkuk?", "jawaban": "buku" },
  { "soal": "Apa yang punya perut tapi tidak bisa kenyang?", "jawaban": "tas" },
  { "soal": "Apa yang punya leher tapi tidak punya kepala?", "jawaban": "baju" },
  { "soal": "Apa yang punya lengan tapi tidak bisa memeluk?", "jawaban": "kursi" },
  { "soal": "Apa yang punya kaki tapi tidak bisa berlari?", "jawaban": "meja" },
  { "soal": "Apa yang punya jari tapi tidak bisa menggenggam?", "jawaban": "sarung tangan" },
  { "soal": "Apa yang punya rambut tapi tidak bisa disisir?", "jawaban": "jagung" },
  { "soal": "Apa yang punya mata tapi tidak bisa menangis?", "jawaban": "jarum" },
  { "soal": "Apa yang punya gigi tapi tidak bisa tertawa?", "jawaban": "gergaji" },
  { "soal": "Apa yang punya lidah tapi tidak bisa menjilat?", "jawaban": "sepatu" },
  { "soal": "Apa yang punya telinga tapi tidak bisa mendengar?", "jawaban": "tangga" },
  { "soal": "Apa yang punya hidung tapi tidak bisa mencium?", "jawaban": "teko" },
  { "soal": "Apa yang punya mulut tapi tidak bisa minum?", "jawaban": "sungai" }
]